export const classes = [
  {
    className: "mage",
    hp: 150,
    // atk: 2000,
    atk: 16,
    int: 150,
    spd: 50,
    agi: 6,
    // agi: 0,
    armor: 4,
    color: "#3FC7EB",
    icon: "mageIcon",
    potions: 2,
    onDef: false,
    ultimUp: true,
  },
  {
    className: "voleur",
    hp: 150,
    atk: 44,
    int: 20,
    spd: 80,
    agi: 7,
    armor: 6,
    color: "#FFF468",
    icon: "rogueIcon",
    potions: 2,
    onDef: false,
    ultimUp: true,
  },
  {
    className: "guerrier",
    hp: 150,
    atk: 130,
    int: 10,
    spd: 30,
    agi: 5,
    armor: 8,
    color: "#C69B6D",
    icon: "warriorIcon",
    potions: 2,
    onDef: false,
    ultimUp: true,
  },
];
